// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgOk5uoNUQ1gLOYZXLzitrUzD6vvsiilc',
    appId: '1:220907967013:web:be5f31e9236fb0c19365cc',
    messagingSenderId: '220907967013',
    projectId: 'flutter-tasks-app-1d0f6',
    authDomain: 'flutter-tasks-app-1d0f6.firebaseapp.com',
    storageBucket: 'flutter-tasks-app-1d0f6.appspot.com',
    measurementId: 'G-4QPLJHDBGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Bs17JTHuJHVt806mFpToUQkvLi2v_j0',
    appId: '1:220907967013:android:1b81bf2928669a2e9365cc',
    messagingSenderId: '220907967013',
    projectId: 'flutter-tasks-app-1d0f6',
    storageBucket: 'flutter-tasks-app-1d0f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtyhSDzc2ESj6sKhfa0pDlkovkJTzPjiw',
    appId: '1:220907967013:ios:047ec7178518ef1a9365cc',
    messagingSenderId: '220907967013',
    projectId: 'flutter-tasks-app-1d0f6',
    storageBucket: 'flutter-tasks-app-1d0f6.appspot.com',
    iosClientId: '220907967013-fd1msh5i6l5ro1n9c789hmba5b3ld7an.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocTasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtyhSDzc2ESj6sKhfa0pDlkovkJTzPjiw',
    appId: '1:220907967013:ios:047ec7178518ef1a9365cc',
    messagingSenderId: '220907967013',
    projectId: 'flutter-tasks-app-1d0f6',
    storageBucket: 'flutter-tasks-app-1d0f6.appspot.com',
    iosClientId: '220907967013-fd1msh5i6l5ro1n9c789hmba5b3ld7an.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocTasksApp',
  );
}
